[2023-09-23T00:14:45.215+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres manual__2023-09-23T00:14:42.073923+00:00 [queued]>
[2023-09-23T00:14:45.225+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres manual__2023-09-23T00:14:42.073923+00:00 [queued]>
[2023-09-23T00:14:45.226+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T00:14:45.227+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-23T00:14:45.227+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T00:14:45.241+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): transfer_data_pgdatabase_postgres> on 2023-09-23 00:14:42.073923+00:00
[2023-09-23T00:14:45.244+0000] {standard_task_runner.py:55} INFO - Started process 675 to run task
[2023-09-23T00:14:45.247+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_multi_table', 'transfer_data_pgdatabase_postgres', 'manual__2023-09-23T00:14:42.073923+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/crt_tbls_trs_data.py', '--cfg-path', '/tmp/tmp268ab6n5']
[2023-09-23T00:14:45.248+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask transfer_data_pgdatabase_postgres
[2023-09-23T00:14:45.297+0000] {task_command.py:376} INFO - Running <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres manual__2023-09-23T00:14:42.073923+00:00 [running]> on host 411713a30e55
[2023-09-23T00:14:45.371+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_multi_table
AIRFLOW_CTX_TASK_ID=transfer_data_pgdatabase_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-09-23T00:14:42.073923+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-23T00:14:42.073923+00:00
[2023-09-23T00:14:45.380+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-23T00:14:45.561+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-23T00:14:45.709+0000] {generic_transfer.py:76} INFO - Extracting data from pgdatabase
[2023-09-23T00:14:45.709+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT * FROM machine_learning_customerchurn;
[2023-09-23T00:14:45.714+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-23T00:14:45.720+0000] {generic_transfer.py:104} INFO - Inserting rows into postgres
[2023-09-23T00:14:45.725+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-23T00:14:45.728+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 105, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedTable: relation "machine_learing_customerchurn" does not exist
LINE 1: INSERT INTO machine_learing_customerchurn  VALUES (1,'MT',73...
                    ^

[2023-09-23T00:14:45.735+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=create_multi_table, task_id=transfer_data_pgdatabase_postgres, execution_date=20230923T001442, start_date=20230923T001445, end_date=20230923T001445
[2023-09-23T00:14:45.801+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 58 for task transfer_data_pgdatabase_postgres (relation "machine_learing_customerchurn" does not exist
LINE 1: INSERT INTO machine_learing_customerchurn  VALUES (1,'MT',73...
                    ^
; 675)
[2023-09-23T00:14:45.821+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-09-23T00:14:45.835+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
