[2023-09-23T11:10:55.821+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_data.transfer_database manual__2023-09-23T11:10:55.011377+00:00 [queued]>
[2023-09-23T11:10:55.835+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_data.transfer_database manual__2023-09-23T11:10:55.011377+00:00 [queued]>
[2023-09-23T11:10:55.835+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T11:10:55.836+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-23T11:10:55.836+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T11:10:55.851+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): transfer_database> on 2023-09-23 11:10:55.011377+00:00
[2023-09-23T11:10:55.856+0000] {standard_task_runner.py:55} INFO - Started process 2023 to run task
[2023-09-23T11:10:55.858+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_data', 'transfer_database', 'manual__2023-09-23T11:10:55.011377+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/transfer_data.py', '--cfg-path', '/tmp/tmpfm5a7fju']
[2023-09-23T11:10:55.859+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask transfer_database
[2023-09-23T11:10:55.916+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_data.transfer_database manual__2023-09-23T11:10:55.011377+00:00 [running]> on host 35dd594c6205
[2023-09-23T11:10:55.979+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data
AIRFLOW_CTX_TASK_ID=transfer_database
AIRFLOW_CTX_EXECUTION_DATE=2023-09-23T11:10:55.011377+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-23T11:10:55.011377+00:00
[2023-09-23T11:10:55.987+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-23T11:10:56.185+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-23T11:10:56.326+0000] {generic_transfer.py:76} INFO - Extracting data from pgdatabase
[2023-09-23T11:10:56.327+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT state,account_length,area_code,phone_number,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn FROM machine_learning_customerchurn;
[2023-09-23T11:10:56.333+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-23T11:10:56.351+0000] {generic_transfer.py:104} INFO - Inserting rows into postgres
[2023-09-23T11:10:56.357+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-23T11:10:56.362+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 105, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedTable: relation "machine_learing_customerchurn" does not exist
LINE 1: INSERT INTO machine_learing_customerchurn  VALUES ('MT',73,4...
                    ^

[2023-09-23T11:10:56.369+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=extract_data, task_id=transfer_database, execution_date=20230923T111055, start_date=20230923T111055, end_date=20230923T111056
[2023-09-23T11:10:56.425+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task transfer_database (relation "machine_learing_customerchurn" does not exist
LINE 1: INSERT INTO machine_learing_customerchurn  VALUES ('MT',73,4...
                    ^
; 2023)
[2023-09-23T11:10:56.434+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-09-23T11:10:56.451+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
