[2023-09-22T23:36:58.280+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2023-09-22T23:36:58.290+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2023-09-22T23:36:58.291+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:36:58.292+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-22T23:36:58.292+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:36:58.303+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): transfer_data_pgdatabase_postgres> on 2023-09-01 00:00:00+00:00
[2023-09-22T23:36:58.307+0000] {standard_task_runner.py:55} INFO - Started process 176 to run task
[2023-09-22T23:36:58.310+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_multi_table', 'transfer_data_pgdatabase_postgres', 'scheduled__2023-09-01T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/crt_tbls_trs_data.py', '--cfg-path', '/tmp/tmpmy44thpq']
[2023-09-22T23:36:58.311+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask transfer_data_pgdatabase_postgres
[2023-09-22T23:36:58.356+0000] {task_command.py:376} INFO - Running <TaskInstance: create_multi_table.transfer_data_pgdatabase_postgres scheduled__2023-09-01T00:00:00+00:00 [running]> on host c71b9a166a04
[2023-09-22T23:36:58.408+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_multi_table
AIRFLOW_CTX_TASK_ID=transfer_data_pgdatabase_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-01T00:00:00+00:00
[2023-09-22T23:36:58.416+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-22T23:36:58.672+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-22T23:36:58.816+0000] {generic_transfer.py:76} INFO - Extracting data from pgdatabase
[2023-09-22T23:36:58.817+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT * FROM postgres.machine_learning_customerchurn;
[2023-09-22T23:36:58.823+0000] {base.py:71} INFO - Using connection ID 'pgdatabase' for task execution.
[2023-09-22T23:36:58.829+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 85, in execute
    results = get_records(self.sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 217, in get_records
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "postgres.machine_learning_customerchurn" does not exist
LINE 1: SELECT * FROM postgres.machine_learning_customerchurn;
                      ^

[2023-09-22T23:36:58.836+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=create_multi_table, task_id=transfer_data_pgdatabase_postgres, execution_date=20230901T000000, start_date=20230922T233658, end_date=20230922T233658
[2023-09-22T23:36:58.849+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task transfer_data_pgdatabase_postgres (relation "postgres.machine_learning_customerchurn" does not exist
LINE 1: SELECT * FROM postgres.machine_learning_customerchurn;
                      ^
; 176)
[2023-09-22T23:36:58.884+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-09-22T23:36:58.902+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
