[2023-09-22T23:44:56.547+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.create_table manual__2023-09-22T23:44:54.156036+00:00 [queued]>
[2023-09-22T23:44:56.558+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.create_table manual__2023-09-22T23:44:54.156036+00:00 [queued]>
[2023-09-22T23:44:56.559+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:44:56.560+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-22T23:44:56.560+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:44:56.573+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-09-22 23:44:54.156036+00:00
[2023-09-22T23:44:56.578+0000] {standard_task_runner.py:55} INFO - Started process 562 to run task
[2023-09-22T23:44:56.580+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_multi_table', 'create_table', 'manual__2023-09-22T23:44:54.156036+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/crt_tbls_trs_data.py', '--cfg-path', '/tmp/tmpjuc53yt8']
[2023-09-22T23:44:56.581+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask create_table
[2023-09-22T23:44:56.629+0000] {task_command.py:376} INFO - Running <TaskInstance: create_multi_table.create_table manual__2023-09-22T23:44:54.156036+00:00 [running]> on host 411713a30e55
[2023-09-22T23:44:56.683+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_multi_table
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-09-22T23:44:54.156036+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-22T23:44:54.156036+00:00
[2023-09-22T23:44:56.690+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-22T23:44:56.693+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS machine_learning_customerchurn(
                state TEXT NULL,
                account_length INTEGER NULL,
                area_code INTEGER NULL,
                phone_number TEXT NULL,
                international_plan TEXT NULL,
                voice_mail_plan TEXT NULL,
                number_vmail_messages INTEGER NULL,
                total_day_minutes FLOAT NULL,
                total_day_calls INTEGER NULL,
                total_day_charge FLOAT NULL,
                total_eve_minutes FLOAT NULL,
                total_eve_calls INTEGER NULL,
                total_eve_charge FLOAT NULL,
                total_night_minutes FLOAT NULL,
                total_night_calls INTEGER NULL,
                total_night_charge FLOAT NULL,
                total_intl_minutes FLOAT NULL,
                total_intl_calls INTEGER NULL,
                total_intl_charge FLOAT NULL,
                customer_service_calls INTEGER NULL,
                churn BOOLEAN NULL
            );
        , parameters: None
[2023-09-22T23:44:56.694+0000] {postgres.py:96} INFO - NOTICE:  relation "machine_learning_customerchurn" already exists, skipping

[2023-09-22T23:44:56.703+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=create_multi_table, task_id=create_table, execution_date=20230922T234454, start_date=20230922T234456, end_date=20230922T234456
[2023-09-22T23:44:56.753+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-22T23:44:56.772+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
